# Generated by Django 6.0.3 on 2026-04-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('tipo_dispositivo', models.CharField(choices=[('maquina', 'Máquina'), ('tracker', 'Tracker'), ('otro', 'Otro')], max_length=20)),
                ('id_dispositivo', models.CharField(max_length=100)),
                ('duda', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
