# Generated by Django 6.0.3 on 2026-04-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ticket_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='nombre',
            new_name='contacto',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='nombre_empresa',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='duda',
            new_name='observaciones',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_dispositivo',
            field=models.IntegerField(),
        ),
    ]
