# Generated by Django 6.0.3 on 2026-04-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_nombre_ticket_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='empresa_transporte',
            field=models.TextField(default='sin empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='portes',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('debido', 'Debido')], default='sin emoresa', max_length=20),
            preserve_default=False,
        ),
    ]
