# Generated by Django 6.0.3 on 2026-04-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ticket_empresa_transporte_ticket_portes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='empresa_transporte',
            field=models.CharField(max_length=100),
        ),
    ]
