# Generated by Django 6.0.3 on 2026-04-29 10:26

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_ticket_empresa_transporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('encargado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=155)),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=150)),
                ('token_sesion', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='tickets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp']), app.models.validate_image_file]),
        ),
    ]
