# Generated by Django 6.0.3 on 2026-05-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usuario',
        ),
    ]
