# Generated by Django 6.0.3 on 2026-05-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_user_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='test@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
