# Generated by Django 6.0.3 on 2026-05-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='token_sesion',
            field=models.CharField(max_length=150),
        ),
    ]
